spring.application.name=talentscout
server.port=8081

# WSO2 Asgardeo OAuth2 / OIDC Configuration
spring.security.oauth2.client.registration.asgardeo.client-id=zctln4uRMbwMWaj2tFOSTuf3908a
spring.security.oauth2.client.registration.asgardeo.client-secret=uXUPT5Um8yHa5nfvsJXyd6sCoW6ia04lu7rTy8RSzZka
spring.security.oauth2.client.registration.asgardeo.scope=openid,profile,email
spring.security.oauth2.client.registration.asgardeo.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.asgardeo.redirect-uri={baseUrl}/login/oauth2/code/asgardeo

spring.security.oauth2.client.provider.asgardeo.issuer-uri=https://api.asgardeo.io/t/orgfzghb/oauth2/token
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/talentscout_db
spring.datasource.username=root
spring.datasource.password=navith123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true